version: '3.8'

services:
  # Serviço da Aplicação Spring Boot (cyphvv)
  app:
    build: .
    container_name: cyphvv-app
    ports:
      - "8080:8080"
    # Lê automaticamente todas as variáveis de ambiente (banco de dados, firebase) do arquivo .env local
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=staging
