spring.application.name=cyphvv
server.port=${PORT:8080}

# spring.profiles.active defines which environment settings are loaded.
# available environments are 'staging' and 'prod'.

# staging and prod use Supabase PostgreSQL.
# staging is an isolated database with the same schema as prod.

spring.profiles.active=staging
spring.flyway.enabled=true

firebase.config.path=${FIREBASE_CREDENTIALS_PATH:cyphvv-firebase-adminsdk-fbsvc-12a4f1c677.json}