# postgree staging connection
spring.datasource.url=${STAGING_DB_URL}
spring.datasource.username=${STAGING_DB_USER}
spring.datasource.password=${STAGING_DB_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

# ddl-auto=validate: Spring DOES NOT manipulate supabase tables, just verify if
# the java entities are aligned to real tables.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true