# H2 configuration
spring.datasource.url=jdbc:h2:mem:cyphvvdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ddl-auto=update: spring DOES manipulate the database automatically
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.flyway.enabled=false