spring.application.name=cyphvv

#spring.profiles.active variable is able to change the actual ambient (database changing).
#the ambients available are 'dev', 'staging' or 'prod'


#the dev ambient uses H2 database, for business rules manutention

#staging and prod ambients are using supabase (postgre) at the moment, but staging is a
#different database with mirrored schema from prod

spring.profiles.active=staging
spring.flyway.enabled=true

firebase.credentials.path=${FIREBASE_CREDENTIALS_PATH:firebase-credentials.json}