spring.application.name=cyphvv

# spring.profiles.active defines which environment settings are loaded.
# available environments are 'staging' and 'prod'.

# staging and prod use Supabase PostgreSQL.
# staging is an isolated database with the same schema as prod.

spring.profiles.active=staging
spring.flyway.enabled=true

firebase.credentials.path=${FIREBASE_CREDENTIALS_PATH:firebase-credentials.json}