# postgree prod connection
spring.datasource.url=${PROD_DB_URL}
spring.datasource.username=${PROD_DB_USER}
spring.datasource.password=${PROD_DB_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

# ddl-auto=none: max security, spring CANT manipulate the database at all
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# show-sql=false: presuming the alterations are already tested, logs are off so the server runs faster
spring.jpa.show-sql=false