package io.github.carlosyamanaka.cyphvv.application.core.usecases;

import io.github.carlosyamanaka.cyphvv.application.core.domain.CardType;
import io.github.carlosyamanaka.cyphvv.application.core.domain.World;
import io.github.carlosyamanaka.cyphvv.application.ports.in.CreateWorldUseCase;
import io.github.carlosyamanaka.cyphvv.application.ports.out.CardTypeRepositoryPort;
import io.github.carlosyamanaka.cyphvv.application.ports.out.WorldRepositoryPort;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;

public class CreateWorldUseCaseImpl implements CreateWorldUseCase {

    private final WorldRepositoryPort worldRepositoryPort;
    private final CardTypeRepositoryPort cardTypeRepositoryPort;

    //@Autowired is not allowed in application core. Application core should be framework-agnostic. The dependency injection will be handled in the configuration layer (e.g., Spring configuration class).
    public CreateWorldUseCaseImpl(WorldRepositoryPort worldRepositoryPort, CardTypeRepositoryPort cardTypeRepositoryPort) {
        this.worldRepositoryPort = worldRepositoryPort;
        this.cardTypeRepositoryPort = cardTypeRepositoryPort;
    }

    @Override
    public World execute(String userId, String worldName) {
        if (userId == null || userId.trim().isEmpty()) {
            throw new IllegalArgumentException("User ID cannot be null or empty");
        }

        //ID is null cause it will be generated by the database when saved.
        World newWorld = new World(
                null,
                userId,
                OffsetDateTime.now(),
                false,
                null,
                worldName
        );

        //it gotta be saved by others because the ID is generated by the database, so we need to save it to get the ID and return the complete World object.
        World savedWorld = worldRepositoryPort.save(newWorld);

        createDefaultCardTypes(savedWorld.getId());

        return savedWorld;
    }

    private void createDefaultCardTypes(Long worldId) {
        List<DefaultCardType> defaults = Arrays.asList(
                new DefaultCardType("Personagem", "user"),
                new DefaultCardType("Evento", "calendar"),
                new DefaultCardType("Batalha", "shield"),
                new DefaultCardType("Quest", "map"),
                new DefaultCardType("Facção", "users"),
                new DefaultCardType("Culto", "eye"),
                new DefaultCardType("Arma", "crosshair"),
                new DefaultCardType("Magia", "star"),
                new DefaultCardType("Localização", "map-pin"),
                new DefaultCardType("Reino", "crown"),
                new DefaultCardType("Lore", "book-open"),
                new DefaultCardType("Religião", "sun"),
                new DefaultCardType("Lenda", "book")
        );

        for (DefaultCardType def : defaults) {
            CardType cardType = new CardType(
                    null,
                    worldId,
                    def.name,
                    def.icon,
                    OffsetDateTime.now(),
                    false,
                    null
            );
            cardTypeRepositoryPort.save(cardType);
        }
    }

    private static class DefaultCardType {
        String name;
        String icon;

        DefaultCardType(String name, String icon) {
            this.name = name;
            this.icon = icon;
        }
    }
}