package io.github.carlosyamanaka.cyphvv.application.core.usecases;

import io.github.carlosyamanaka.cyphvv.application.core.domain.World;
import io.github.carlosyamanaka.cyphvv.application.ports.in.CreateWorldUseCase;
import io.github.carlosyamanaka.cyphvv.application.ports.out.WorldRepositoryPort;

import java.time.OffsetDateTime;

public class CreateWorldUseCaseImpl implements CreateWorldUseCase {

    private final WorldRepositoryPort worldRepositoryPort;

    //@Autowired is not allowed in application core. Application core should be framework-agnostic. The dependency injection will be handled in the configuration layer (e.g., Spring configuration class).
    public CreateWorldUseCaseImpl(WorldRepositoryPort worldRepositoryPort) {
        this.worldRepositoryPort = worldRepositoryPort;
    }

    @Override
    public World execute(String userId, String worldName) {
        if (userId == null || userId.trim().isEmpty()) {
            throw new IllegalArgumentException("User ID cannot be null or empty");
        }

        //ID is null cause it will be generated by the database when saved.
        World newWorld = new World(
                null,
                userId,
                OffsetDateTime.now(),
                false,
                null,
                worldName
        );

        //it gotta be saved by others because the ID is generated by the database, so we need to save it to get the ID and return the complete World object.
        return worldRepositoryPort.save(newWorld);
    }
}